# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ColorsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ColorsConverterWindow(object):
    def setupUi(self, ColorsConverterWindow):
        ColorsConverterWindow.setObjectName("ColorsConverterWindow")
        ColorsConverterWindow.resize(839, 691)
        self.centralwidget = QtWidgets.QWidget(ColorsConverterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(380, 210, 20, 431))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 410, 841, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.rgb_r_slider = QtWidgets.QSlider(self.centralwidget)
        self.rgb_r_slider.setGeometry(QtCore.QRect(20, 271, 161, 20))
        self.rgb_r_slider.setMaximum(255)
        self.rgb_r_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rgb_r_slider.setObjectName("rgb_r_slider")
        self.rgb_g_slider = QtWidgets.QSlider(self.centralwidget)
        self.rgb_g_slider.setGeometry(QtCore.QRect(20, 320, 161, 20))
        self.rgb_g_slider.setMaximum(255)
        self.rgb_g_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rgb_g_slider.setObjectName("rgb_g_slider")
        self.rgb_b_slider = QtWidgets.QSlider(self.centralwidget)
        self.rgb_b_slider.setGeometry(QtCore.QRect(20, 370, 161, 21))
        self.rgb_b_slider.setMaximum(255)
        self.rgb_b_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rgb_b_slider.setObjectName("rgb_b_slider")
        self.color_frame = QtWidgets.QFrame(self.centralwidget)
        self.color_frame.setGeometry(QtCore.QRect(260, 20, 301, 161))
        self.color_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.color_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.color_frame.setObjectName("color_frame")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 210, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 210, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 430, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 430, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 250, 31, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 51, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 41, 17))
        self.label_7.setObjectName("label_7")
        self.cmyk_c_slider = QtWidgets.QSlider(self.centralwidget)
        self.cmyk_c_slider.setGeometry(QtCore.QRect(410, 260, 160, 21))
        self.cmyk_c_slider.setMaximum(100)
        self.cmyk_c_slider.setPageStep(1)
        self.cmyk_c_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cmyk_c_slider.setObjectName("cmyk_c_slider")
        self.cmyk_m_slider = QtWidgets.QSlider(self.centralwidget)
        self.cmyk_m_slider.setGeometry(QtCore.QRect(410, 300, 160, 21))
        self.cmyk_m_slider.setMaximum(100)
        self.cmyk_m_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cmyk_m_slider.setObjectName("cmyk_m_slider")
        self.cmyk_y_slider = QtWidgets.QSlider(self.centralwidget)
        self.cmyk_y_slider.setGeometry(QtCore.QRect(410, 340, 160, 21))
        self.cmyk_y_slider.setMaximum(100)
        self.cmyk_y_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cmyk_y_slider.setObjectName("cmyk_y_slider")
        self.cmyk_k_slider = QtWidgets.QSlider(self.centralwidget)
        self.cmyk_k_slider.setGeometry(QtCore.QRect(410, 380, 160, 21))
        self.cmyk_k_slider.setMaximum(100)
        self.cmyk_k_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cmyk_k_slider.setObjectName("cmyk_k_slider")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 240, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(410, 280, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(410, 320, 67, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(410, 360, 67, 17))
        self.label_11.setObjectName("label_11")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 200, 831, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 470, 67, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 520, 81, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 570, 67, 17))
        self.label_14.setObjectName("label_14")
        self.hsl_h_slider = QtWidgets.QSlider(self.centralwidget)
        self.hsl_h_slider.setGeometry(QtCore.QRect(20, 490, 160, 21))
        self.hsl_h_slider.setMaximum(360)
        self.hsl_h_slider.setOrientation(QtCore.Qt.Horizontal)
        self.hsl_h_slider.setObjectName("hsl_h_slider")
        self.hsl_s_slider = QtWidgets.QSlider(self.centralwidget)
        self.hsl_s_slider.setGeometry(QtCore.QRect(20, 540, 160, 21))
        self.hsl_s_slider.setMaximum(100)
        self.hsl_s_slider.setOrientation(QtCore.Qt.Horizontal)
        self.hsl_s_slider.setObjectName("hsl_s_slider")
        self.hsl_l_slider = QtWidgets.QSlider(self.centralwidget)
        self.hsl_l_slider.setGeometry(QtCore.QRect(20, 590, 160, 21))
        self.hsl_l_slider.setMaximum(100)
        self.hsl_l_slider.setOrientation(QtCore.Qt.Horizontal)
        self.hsl_l_slider.setObjectName("hsl_l_slider")
        self.lab_l_slider = QtWidgets.QSlider(self.centralwidget)
        self.lab_l_slider.setGeometry(QtCore.QRect(410, 490, 160, 21))
        self.lab_l_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lab_l_slider.setObjectName("lab_l_slider")
        self.lab_a_slider = QtWidgets.QSlider(self.centralwidget)
        self.lab_a_slider.setGeometry(QtCore.QRect(410, 540, 160, 21))
        self.lab_a_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lab_a_slider.setObjectName("lab_a_slider")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(410, 470, 91, 17))
        self.label_15.setObjectName("label_15")
        self.lab_b_slider = QtWidgets.QSlider(self.centralwidget)
        self.lab_b_slider.setGeometry(QtCore.QRect(410, 590, 160, 21))
        self.lab_b_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lab_b_slider.setObjectName("lab_b_slider")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(410, 520, 81, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(410, 570, 67, 17))
        self.label_17.setObjectName("label_17")
        self.rgb_red_line = QtWidgets.QLineEdit(self.centralwidget)
        self.rgb_red_line.setGeometry(QtCore.QRect(190, 270, 61, 27))
        self.rgb_red_line.setObjectName("rgb_red_line")
        self.rgb_green_line = QtWidgets.QLineEdit(self.centralwidget)
        self.rgb_green_line.setGeometry(QtCore.QRect(190, 320, 61, 27))
        self.rgb_green_line.setObjectName("rgb_green_line")
        self.rgb_blue_line = QtWidgets.QLineEdit(self.centralwidget)
        self.rgb_blue_line.setGeometry(QtCore.QRect(190, 370, 61, 27))
        self.rgb_blue_line.setObjectName("rgb_blue_line")
        self.hsl_hue_line = QtWidgets.QLineEdit(self.centralwidget)
        self.hsl_hue_line.setGeometry(QtCore.QRect(190, 490, 61, 27))
        self.hsl_hue_line.setObjectName("hsl_hue_line")
        self.hsl_sat_line = QtWidgets.QLineEdit(self.centralwidget)
        self.hsl_sat_line.setGeometry(QtCore.QRect(190, 540, 61, 27))
        self.hsl_sat_line.setObjectName("hsl_sat_line")
        self.hsl_light_line = QtWidgets.QLineEdit(self.centralwidget)
        self.hsl_light_line.setGeometry(QtCore.QRect(190, 590, 61, 27))
        self.hsl_light_line.setObjectName("hsl_light_line")
        self.cmyk_c_line = QtWidgets.QLineEdit(self.centralwidget)
        self.cmyk_c_line.setGeometry(QtCore.QRect(580, 260, 61, 27))
        self.cmyk_c_line.setObjectName("cmyk_c_line")
        self.cmyk_m_line = QtWidgets.QLineEdit(self.centralwidget)
        self.cmyk_m_line.setGeometry(QtCore.QRect(580, 300, 61, 27))
        self.cmyk_m_line.setObjectName("cmyk_m_line")
        self.cmyk_k_line = QtWidgets.QLineEdit(self.centralwidget)
        self.cmyk_k_line.setGeometry(QtCore.QRect(580, 380, 61, 27))
        self.cmyk_k_line.setObjectName("cmyk_k_line")
        self.cmyk_y_line = QtWidgets.QLineEdit(self.centralwidget)
        self.cmyk_y_line.setGeometry(QtCore.QRect(580, 340, 61, 27))
        self.cmyk_y_line.setObjectName("cmyk_y_line")
        self.lab_b_line = QtWidgets.QLineEdit(self.centralwidget)
        self.lab_b_line.setGeometry(QtCore.QRect(580, 590, 61, 27))
        self.lab_b_line.setObjectName("lab_b_line")
        self.lab_a_line = QtWidgets.QLineEdit(self.centralwidget)
        self.lab_a_line.setGeometry(QtCore.QRect(580, 540, 61, 27))
        self.lab_a_line.setObjectName("lab_a_line")
        self.lab_l_line = QtWidgets.QLineEdit(self.centralwidget)
        self.lab_l_line.setGeometry(QtCore.QRect(580, 490, 61, 27))
        self.lab_l_line.setObjectName("lab_l_line")
        ColorsConverterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ColorsConverterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 25))
        self.menubar.setObjectName("menubar")
        ColorsConverterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ColorsConverterWindow)
        self.statusbar.setObjectName("statusbar")
        ColorsConverterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ColorsConverterWindow)
        QtCore.QMetaObject.connectSlotsByName(ColorsConverterWindow)

    def retranslateUi(self, ColorsConverterWindow):
        _translate = QtCore.QCoreApplication.translate
        ColorsConverterWindow.setWindowTitle(_translate("ColorsConverterWindow", "MainWindow"))
        self.label.setText(_translate("ColorsConverterWindow", "RGB"))
        self.label_2.setText(_translate("ColorsConverterWindow", "CMYK"))
        self.label_3.setText(_translate("ColorsConverterWindow", "HSL"))
        self.label_4.setText(_translate("ColorsConverterWindow", "Lab"))
        self.label_5.setText(_translate("ColorsConverterWindow", "red"))
        self.label_6.setText(_translate("ColorsConverterWindow", "green"))
        self.label_7.setText(_translate("ColorsConverterWindow", "blue"))
        self.label_8.setText(_translate("ColorsConverterWindow", "cyan"))
        self.label_9.setText(_translate("ColorsConverterWindow", "magenta"))
        self.label_10.setText(_translate("ColorsConverterWindow", "yellow"))
        self.label_11.setText(_translate("ColorsConverterWindow", "key"))
        self.label_12.setText(_translate("ColorsConverterWindow", "hue"))
        self.label_13.setText(_translate("ColorsConverterWindow", "saturation"))
        self.label_14.setText(_translate("ColorsConverterWindow", "lightness"))
        self.label_15.setText(_translate("ColorsConverterWindow", "luminance"))
        self.label_16.setText(_translate("ColorsConverterWindow", "a"))
        self.label_17.setText(_translate("ColorsConverterWindow", "b"))
